default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gorman

test:
  <<: *default
  database: gorman_test

production:
  url: <%= ENV["DATABASE_URL"] %>
