
# CREATE TEAMS
# ------------

Team.create(city: "Arizona", name: "Cardinals", abbr: "ARI")
Team.create(city: "Atlanta", name: "Falcons", abbr: "ATL")
Team.create(city: "Baltimore", name: "Ravens", abbr: "BAL")
Team.create(city: "Buffalo", name: "Bills", abbr: "BUF")
Team.create(city: "Carolina", name: "Panthers", abbr: "CAR")
Team.create(city: "Chicago", name: "Bears", abbr: "CHI")
Team.create(city: "Cincinnati", name: "Bengals", abbr: "CIN")
Team.create(city: "Cleveland", name: "Browns", abbr: "CLE")
Team.create(city: "Dallas", name: "Cowboys", abbr: "DAL")
Team.create(city: "Denver", name: "Broncos", abbr: "DEN")
Team.create(city: "Detroit", name: "Lions", abbr: "DET")
Team.create(city: "Green Bay", name: "Packers", abbr: "GB")
Team.create(city: "Houston", name: "Texans", abbr: "HOU")
Team.create(city: "Indianapolis", name: "Colts", abbr: "IND")
Team.create(city: "Jacksonville", name: "Jaguars", abbr: "JAC")
Team.create(city: "Kansas City", name: "Chiefs", abbr: "KC")
Team.create(city: "Miami", name: "Dolphins", abbr: "MIA")
Team.create(city: "Minnesota", name: "Vikings", abbr: "MIN")
Team.create(city: "New England", name: "Patriots", abbr: "NE")
Team.create(city: "New Orleans", name: "Saints", abbr: "NO")
Team.create(city: "New York", name: "Giants", abbr: "NYG")
Team.create(city: "New York", name: "Jets", abbr: "NYJ")
Team.create(city: "Oakland", name: "Raiders", abbr: "OAK")
Team.create(city: "Philadelphia", name: "Eagles", abbr: "PHI")
Team.create(city: "Pittsburgh", name: "Steelers", abbr: "PIT")
Team.create(city: "San Diego", name: "Chargers", abbr: "SD")
Team.create(city: "San Francisco", name: "49ers", abbr: "SF")
Team.create(city: "Seattle", name: "Seahawks", abbr: "SEA")
Team.create(city: "St. Louis", name: "Rams", abbr: "STL")
Team.create(city: "Tampa Bay", name: "Buccaneers", abbr: "TB")
Team.create(city: "Tennessee", name: "Titans", abbr: "TEN")
Team.create(city: "Washington", name: "Redskins", abbr: "WAS")
